version: '3'
services:
  app:
    build: .
    container_name: app
    networks:
      - net_app
    ports:
      - 8080:80
    depends_on:
      - redis

  redis:
    image: redis:7.2-rc2-alpine3.18
    container_name: redis
    networks:
      - net_app
networks:
  net_app:
    driver: bridge