version: '3'
services:
  app:
    image: tiztan21/flaskweb:1.6
    container_name: service-flask-app
    ports:
      - 8000:8000
    networks:
      - net_py

  consumer:
    image: tiztan21/consumer:1.0
    container_name: consumer
    environment:
      - LOCAL=true
      - PYTHONUNBUFFERED="1"
    networks:
      - net_py
networks:
  net_py:
    driver: bridge